import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the initial state for the counter
interface CounterState {
    value: number;
}

const initialState: CounterState = {
    value: 0,
};

// Create a slice for the counter feature
const counterSlice = createSlice({
    name: "counter",
    initialState,
    reducers: {
        // Define reducers for incrementing and decrementing the counter
        increment(state) {
            state.value += 1;
        },
        decrement(state) {
            state.value -= 1;
        },
        // Define a reducer for incrementing the counter by a specific amount
        incrementByAmount(state, action: PayloadAction<number>) {
            state.value += action.payload;
        },
    },
});

// Export actions generated by the slice
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// Export the reducer function generated by the slice
export default counterSlice.reducer;
